language: php

php:
  - 5.3
  - 7.1

before_install:
  - '[[ "$TRAVIS_PHP_VERSION" != hhvm* ]] && (php --ini | grep xdebug) && phpenv config-rm xdebug.ini || true'

install:
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

before_deploy:
  - bin/package -v x1

deploy:
  provider: releases
  api_key:
    secure: LL8koDM1xDqzF9t0URHvmMPyWjojyd4PeZ7IW7XYgyvD6n1H6GYrVAeKCh5wfUKFbwHoa9s5AAn6pLzra00bODVkPTmUH+FSMWz9JKLw9ODAn8HvN7C+IooxmeClGHFZc0TfHfya8/D1E9C1iXtGGEoE/GqtaYq/z0C1DLpO0OU=
  file:
    - dist/psysh-${PKG_VERSION}.tar.gz
    - dist/psysh-${PKG_VERSION}-compat.tar.gz
  skip_cleanup: true
  on:
    branch: test-build
    repo: bobthecow/psysh
